# Setup
title:               Przemek Zientala
tagline:             'Notes on things that matter to me'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://slazien.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Przemek Zientala
  url:               https://www.linkedin.com/in/pzientala/
  email:             p.zientala.1995@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
