# Setup
title:               Przemek Zientala
tagline:             'Notes on things that matter to me'
description:         'This is my little, personal space on the vast internet; welcome! 
I hope you will enjoy your stay and learn a thing or two.'
url:                 http://slazien.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Przemek Zientala
  url:               https://www.linkedin.com/in/pzientala/
  email:             p.zientala.1995@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
